### ISSUE TITLE
dict to dataframe conversion in mat2bin

### ISSUE THREAD

**Issue by xywang01** [OlivierCodol/kinarm-matlab2python#1]
Not sure how relevant this is for others, but in our output, the mat-converted dictionary may contain key-value pairs of size 0, which would raise an error when converting the dictionary to DataFrame. 

Therefore, instead of:

`dataframes_dict = {k: pd.DataFrame(mat2dict(MAT, k)) for k in MAT.keys()}`

I used the following:

`
dataframes_dict = {}
for k in MAT.keys():
    temp_dict = mat2dict(MAT, k)

    # Find the maximum size among non-empty arrays
    max_size = max(len(arr) for arr in temp_dict.values() if len(arr) > 0)

    # Replace empty arrays with arrays of the same size
    for key, value in temp_dict.items():
        if len(value) == 0:
            temp_dict[key] = np.zeros(max_size, dtype=value.dtype)

    dataframes_dict[k] = pd.DataFrame(temp_dict)
`

**Comment by OlivierCodol** [comment]
Hi @xywang01, thanks for bringing this up.

I am a bit wary of "making up" float data, which this would do by creating 0-padded arrays. Maybe a solution would be to pad it with `np.nan` or `None` arrays?

**Comment by xywang01** [comment]
That makes sense! Padding with either would be more stable. 

In any case, thanks for making this great tool! It has been super helpful!

**Comment by OlivierCodol** [comment]
My pleasure! Feel free to send a PR if you fix this so I can look it up and merge it for the future maybe
